system/supervisor: !local: Add sanity checkes in the SlackBuild

diff --git a/system/supervisor/supervisor.SlackBuild b/system/supervisor/supervisor.SlackBuild
--- a/system/supervisor/supervisor.SlackBuild
+++ b/system/supervisor/supervisor.SlackBuild
@@ -59,6 +59,13 @@ cd $PRGNAM-$VERSION
 chown -R root:root .
 chmod -R a-st,u+rwX,go-w+rX .
 
+SKEL_CONFIG_CHECKSUM=($(md5sum supervisor/skel/sample.conf))
+if [[ "26d67b757f2a9af58f9ecf5c03db6766" != ${SKEL_CONFIG_CHECKSUM} ]]; then
+  printf  'error: Config file "supervisor/skel/sample.conf" has changed.\n'`
+         `'       Ensure that config file provided with the SlackBuild is in sync.\n'
+  exit 1
+fi
+
 python3 setup.py install --root=$PKG
 
 # NOTE:
